"""Seed realistic, complete example documents into the `documents` table for
the two bundled fictitious clients (Jordan Ellis, Morgan Alvarez).

These are hand-authored (not generated by a live LLM call, to keep this
repo's setup free to run) but the classification/extraction VALUES are fed
through the real, deterministic `app/tools/organizer.py::cross_check_document`
and `recompute_client_completeness` functions -- exactly what the live graph
calls -- so the cross-check flags and organizer completeness shown are
authentic, not hand-typed guesses. They exist so the "Client Organizer /
Example Analyses" page has real, varied content (including a deliberately
INCOMPLETE client and a caught duplicate) before a visitor uploads anything
themselves.

Run with:
    python -m scripts.seed_examples

Requires `scripts/seed_clients.py` to have already run (the clients this
script attaches documents to must already exist).
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

from app.db.models import Document
from app.db.session import SessionLocal
from app.tools.organizer import cross_check_document, recompute_client_completeness


def _iso(dt: datetime) -> str:
    return dt.isoformat()


def _trace(base: datetime, node: str, minutes: float, summary: str) -> dict:
    return {"node": node, "timestamp": _iso(base + timedelta(minutes=minutes)), "summary": summary}


def _seed_one(
    *,
    doc_id: str,
    client_id: str,
    original_filename: str,
    doc_type: str,
    schema_name: str,
    confidence: float,
    extracted_fields: dict,
    human_decision: str,
    human_feedback: str,
    days_ago: float,
    review_delay_minutes: float,
) -> None:
    with SessionLocal() as db:
        if db.get(Document, doc_id) is not None:
            print(f"[skip] document {doc_id!r} already seeded")
            return

    flags = cross_check_document(client_id, doc_type, extracted_fields)
    t0 = datetime.now(timezone.utc) - timedelta(days=days_ago)

    if human_decision == "reject":
        final_status, status = "rejected", "rejected"
    else:
        final_status, status = "added_to_organizer", "completed"

    trace = [
        _trace(t0, "ingest", 0.0, f"Detected PDF; extracted text from {original_filename}."),
        _trace(t0, "classify", 0.3, f"Classified as {doc_type!r} (confidence={confidence:.2f})."),
        _trace(t0, f"extract_{doc_type.lower().replace('-', '')}", 0.6, f"Extracted fields using {schema_name}."),
        _trace(t0, "cross_check", 0.8, f"{len(flags)} flag(s) found."),
        _trace(t0, "review", review_delay_minutes, f"Preparer decision={human_decision} | {human_feedback[:200]}"),
        _trace(t0, "finalize", review_delay_minutes + 0.1, f"Document finalized with status={final_status}."),
    ]
    state_snapshot = {
        "doc_type": doc_type,
        "classification_confidence": confidence,
        "extraction_schema_used": schema_name,
        "extracted_fields": extracted_fields,
        "cross_check_flags": flags,
        "human_decision": human_decision,
        "human_feedback": human_feedback,
        "final_status": final_status,
        "status": status,
    }

    doc = Document(
        id=doc_id,
        client_id=client_id,
        original_filename=original_filename,
        doc_type=doc_type,
        classification_confidence=confidence,
        status=status,
        final_status=final_status,
        extracted_fields=extracted_fields,
        cross_check_flags=flags,
        trace=trace,
        state_snapshot=state_snapshot,
        error=None,
        created_at=t0,
        updated_at=t0 + timedelta(minutes=review_delay_minutes + 0.1),
    )
    with SessionLocal() as db:
        db.add(doc)
        db.commit()
    print(f"[seeded] document {doc_id!r} ({doc_type}, {final_status})")


def seed() -> None:
    # ---------------------------------------------------------------
    # Jordan Ellis -- COMPLETE client: W-2 + 1099-NEC + 1099-INT all
    # received, plus a supplementary bank statement that is not on the
    # checklist (demonstrates the "unexpected document" info flag).
    # ---------------------------------------------------------------
    _seed_one(
        doc_id="seed-w2-cascade-ellis",
        client_id="jordan-ellis",
        original_filename="W2_Cascade_Retail_Group_Jordan_Ellis.pdf",
        doc_type="W-2",
        schema_name="W2Fields",
        confidence=0.97,
        extracted_fields={
            "employer_name": "Cascade Retail Group",
            "employer_ein": "84-1234567",
            "employee_name": "Jordan Ellis",
            "employee_ssn": "412-34-5678",
            "tax_year": 2025,
            "box1_wages": 28450.00,
            "box2_federal_tax_withheld": 2100.00,
            "box3_social_security_wages": 28450.00,
            "box4_social_security_tax_withheld": 1763.90,
            "box5_medicare_wages": 28450.00,
            "box6_medicare_tax_withheld": 412.53,
            "box16_state_wages": 28450.00,
            "box17_state_income_tax": 854.00,
            "state": "OH",
        },
        human_decision="approve",
        human_feedback="Matches last year's employer; values look right.",
        days_ago=12,
        review_delay_minutes=30,
    )
    _seed_one(
        doc_id="seed-1099int-harborview-ellis",
        client_id="jordan-ellis",
        original_filename="1099INT_Harborview_Savings_Bank_Jordan_Ellis.pdf",
        doc_type="1099-INT",
        schema_name="Form1099INTFields",
        confidence=0.95,
        extracted_fields={
            "payer_name": "Harborview Savings Bank",
            "payer_tin": "45-6789012",
            "recipient_name": "Jordan Ellis",
            "recipient_tin": "412-34-5678",
            "tax_year": 2025,
            "box1_interest_income": 184.32,
            "box4_federal_tax_withheld": 0.0,
        },
        human_decision="approve",
        human_feedback="Small savings account, matches prior years.",
        days_ago=9,
        review_delay_minutes=12,
    )
    _seed_one(
        doc_id="seed-1099nec-bluepeak-ellis",
        client_id="jordan-ellis",
        original_filename="1099NEC_Bluepeak_Design_Studio_Jordan_Ellis.pdf",
        doc_type="1099-NEC",
        schema_name="Form1099NECFields",
        confidence=0.96,
        extracted_fields={
            "payer_name": "Bluepeak Design Studio",
            "payer_tin": "91-2345678",
            "recipient_name": "Jordan Ellis",
            "recipient_tin": "412-34-5678",
            "tax_year": 2025,
            "box1_nonemployee_compensation": 6200.00,
            "box4_federal_tax_withheld": 0.0,
        },
        human_decision="approve",
        human_feedback="Confirmed with client -- freelance logo design project.",
        days_ago=5,
        review_delay_minutes=20,
    )
    _seed_one(
        doc_id="seed-bankstmt-harborview-ellis",
        client_id="jordan-ellis",
        original_filename="Harborview_Savings_Bank_Statement_Jordan_Ellis.pdf",
        doc_type="bank-statement",
        schema_name="BankStatementFields",
        confidence=0.9,
        extracted_fields={
            "bank_name": "Harborview Savings Bank",
            "account_holder_name": "Jordan Ellis",
            "account_number_last4": "7741",
            "statement_period_start": "2025-01-01",
            "statement_period_end": "2025-12-31",
            "total_interest_earned": 184.32,
        },
        human_decision="approve",
        human_feedback="Client sent this alongside the 1099-INT; kept for backup, not required.",
        days_ago=4,
        review_delay_minutes=8,
    )

    # ---------------------------------------------------------------
    # Morgan Alvarez -- INCOMPLETE client: W-2 (Fenwick), K-1, and
    # 1099-DIV received; the second W-2 (Northbridge Analytics, the new
    # job from July) has NOT been received, so the checklist should
    # flag it as still missing. Also includes a rejected accidental
    # duplicate re-upload of the Fenwick W-2, to demonstrate the
    # duplicate-document catch.
    # ---------------------------------------------------------------
    _seed_one(
        doc_id="seed-w2-fenwick-alvarez",
        client_id="morgan-alvarez",
        original_filename="W2_Fenwick_Logistics_Inc_Morgan_Alvarez.pdf",
        doc_type="W-2",
        schema_name="W2Fields",
        confidence=0.97,
        extracted_fields={
            "employer_name": "Fenwick Logistics Inc",
            "employer_ein": "27-9876543",
            "employee_name": "Morgan Alvarez",
            "employee_ssn": "558-12-9034",
            "tax_year": 2025,
            "box1_wages": 41200.00,
            "box2_federal_tax_withheld": 3850.00,
            "box3_social_security_wages": 41200.00,
            "box4_social_security_tax_withheld": 2554.40,
            "box5_medicare_wages": 41200.00,
            "box6_medicare_tax_withheld": 597.40,
            "box16_state_wages": 41200.00,
            "box17_state_income_tax": 1236.00,
            "state": "IL",
        },
        human_decision="approve",
        human_feedback="First-half-of-year employer, confirmed with client.",
        days_ago=14,
        review_delay_minutes=25,
    )
    _seed_one(
        doc_id="seed-k1-alvarez-holdings",
        client_id="morgan-alvarez",
        original_filename="K1_Alvarez_Family_Holdings_LLC_Morgan_Alvarez.pdf",
        doc_type="K-1",
        schema_name="K1Fields",
        confidence=0.93,
        extracted_fields={
            "partnership_name": "Alvarez Family Holdings LLC",
            "partnership_ein": "58-4433221",
            "partner_name": "Morgan Alvarez",
            "partner_ssn_or_tin": "558-12-9034",
            "tax_year": 2025,
            "box1_ordinary_business_income": 3200.00,
            "box2_net_rental_real_estate_income": 0.0,
            "box14_self_employment_earnings": 0.0,
        },
        human_decision="approve",
        human_feedback="Consistent with the family LLC's K-1 in prior years.",
        days_ago=10,
        review_delay_minutes=45,
    )
    _seed_one(
        doc_id="seed-1099div-crestline-alvarez",
        client_id="morgan-alvarez",
        original_filename="1099DIV_Crestline_Investments_Morgan_Alvarez.pdf",
        doc_type="1099-DIV",
        schema_name="Form1099DIVFields",
        confidence=0.95,
        extracted_fields={
            "payer_name": "Crestline Investments",
            "payer_tin": "36-1122334",
            "recipient_name": "Morgan Alvarez",
            "recipient_tin": "558-12-9034",
            "tax_year": 2025,
            "box1a_total_ordinary_dividends": 912.44,
            "box1b_qualified_dividends": 780.00,
            "box2a_total_capital_gain_distributions": 145.10,
            "box4_federal_tax_withheld": 0.0,
        },
        human_decision="approve",
        human_feedback="Brokerage 1099-DIV, matches the account statement.",
        days_ago=6,
        review_delay_minutes=15,
    )
    _seed_one(
        doc_id="seed-w2-fenwick-duplicate-alvarez",
        client_id="morgan-alvarez",
        original_filename="W2_Fenwick_Logistics_Inc_Morgan_Alvarez_RESCAN.pdf",
        doc_type="W-2",
        schema_name="W2Fields",
        confidence=0.96,
        extracted_fields={
            "employer_name": "Fenwick Logistics Inc",
            "employer_ein": "27-9876543",
            "employee_name": "Morgan Alvarez",
            "employee_ssn": "558-12-9034",
            "tax_year": 2025,
            "box1_wages": 41200.00,
            "box2_federal_tax_withheld": 3850.00,
            "box3_social_security_wages": 41200.00,
            "box4_social_security_tax_withheld": 2554.40,
            "box5_medicare_wages": 41200.00,
            "box6_medicare_tax_withheld": 597.40,
            "box16_state_wages": 41200.00,
            "box17_state_income_tax": 1236.00,
            "state": "IL",
        },
        human_decision="reject",
        human_feedback="Client accidentally re-scanned and re-uploaded the same Fenwick W-2; already on file. Rejecting the duplicate.",
        days_ago=3,
        review_delay_minutes=5,
    )

    for client_id in ("jordan-ellis", "morgan-alvarez"):
        result = recompute_client_completeness(client_id)
        print(f"[organizer] {client_id}: {result}")


if __name__ == "__main__":
    seed()
